image: itsplus/s2shape-test-harness

stages:
  - build
  - test

variables:
  MINIO_ACCESS_KEY: user
  MINIO_SECRET_KEY: password
  S3_ACCESS_KEY: user
  S3_SECRET_KEY: password
  S3_REGION: us-east-1
  S3_CONTAINER: bucket
  S3_HOST: http://minio:9000

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: minio/minio
      alias: minio
      command: [ server, /data ]

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/S3SupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init S3SupplyCollector s3://$S3_ACCOUNT_NAME:$S3_ACCOUNT_KEY@$S3_REGION/$S3_CONTAINER,override_host=$S3_HOST
    - dotnet SupplyCollectorDataLoader.dll -xunit S3SupplyCollector s3://$S3_ACCOUNT_NAME:$S3_ACCOUNT_KEY@$S3_REGION/$S3_CONTAINER,override_host=$S3_HOST
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: minio/minio
      alias: minio
      command: [ server, /data ]

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/AzureBlobSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init S3SupplyCollector s3://$S3_ACCOUNT_NAME:$S3_ACCOUNT_KEY@$S3_REGION/$S3_CONTAINER,override_host=$S3_HOST
    - dotnet SupplyCollectorDataLoader.dll -xunit S3SupplyCollector s3://$S3_ACCOUNT_NAME:$S3_ACCOUNT_KEY@$S3_REGION/$S3_CONTAINER,override_host=$S3_HOST
    - dotnet SupplyCollectorDataLoader.dll -samples S3SupplyCollector s3://$S3_ACCOUNT_NAME:$S3_ACCOUNT_KEY@$S3_REGION/$S3_CONTAINER,override_host=$S3_HOST TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/AzureBlobSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness

