image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  MINIO_ACCESS_KEY: user
  MINIO_SECRET_KEY: password
  S3_ACCESS_KEY: user
  S3_SECRET_KEY: password
  S3_REGION: us-east-1
  S3_CONTAINER: bucket
  S3_HOST: http://minio:9000

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: itsplus/s2shape-s3-test
      alias: minio
      command: [server, "/data"]

  script:
    - dotnet build
    - dotnet test
